apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-jobs-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-jobs-helloworld
  template:
    metadata:
      labels:
        app: batch-jobs-helloworld
    spec:
      containers:
      - name: aci-helloworld
        image: mcr.microsoft.com/azuredocs/aci-helloworld
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - batchpool001
